### ISSUE TITLE
compile error on Linux : fixed !

### ISSUE THREAD

**Issue by tissatussa** [3met/Valkyrie#8]
i just discovered your chess engine and i managed to compile v1.0 on Linux (Xubuntu 22.04) but i had to correct some code .. it seems to run fine in CuteChess (GUI) !

when compiling i got this error :

```
[...]
g++ -std=c++17 -O3 -Ofast -Wshadow -Wdouble-promotion -Wformat-overflow -Wformat-truncation -fno-common -pthread -D LINUX -c "src/uci.cpp" -o "build/main/uci.o" -I include
src/uci.cpp: In member function ‘void UCI::noParallelManager()’:
src/uci.cpp:66:30: error: ‘sleep_for’ is not a member of ‘std::this_thread’
   66 |                 this_thread::sleep_for(queueWaitTime);
      |                              ^~~~~~~~~
src/uci.cpp: In member function ‘void UCI::run()’:
src/uci.cpp:107:54: error: ‘sleep_for’ is not a member of ‘std::this_thread’
  107 |                                         this_thread::sleep_for(span);
      |                                                      ^~~~~~~~~
make: *** [Makefile:73: build/main/uci.o] Error 1
```

i found a solution here :

error: 'sleep_for' is not a member of 'std::this_thread'
https://github.com/linuxdeepin/developer-center/issues/2314

so i fixed the issue by adding `#include <thread>` on top of the file `src/uci.cpp` and compilation went OK.

your code setup is rather unusual, i find the binary in `bin/` but it seems the engine also needs the folder `data` .. normally a (UCI) engine is just 1 file .. although your data folder is about 10 Mb, you could try to include all data into one binary ?! Maybe compress the data and auto extract at execution ?

tip : you should mention this engine is UCI, also by adding that label in the GitHub project ..

btw. i don't understand your info _Thread model must be posix (check with gcc -v)_ but i had no problems with it (after my fix).

**Comment by 3met** [comment]
I was able to replicate the error in Xubuntu 22.04. Adding `#include <thread>` seemed to work for me too so I'll add that in future versions.

Also I've added the UCI tag.

I'm planning to overhaul the engine data with time. Most of that 10Mb is an opening book.
